// CRED series registry. Every mapping below was verified live on 2026-10-09
// against Statistics Canada WDS or Bank of Canada Valet (see verification-report.md).
// LFS vectors (14-10-0287-01) were verified against StatCan's official full-table
// CSV for the 2026-09-04 release because WDS data endpoints return HTTP 409
// (table locked) for that survey during the nightly refresh window.

export type SourceKind = 'statcan' | 'boc';

export type CategorySlug =
  | 'money-banking-finance'
  | 'population-employment-labour'
  | 'national-accounts'
  | 'production-business-activity'
  | 'prices'
  | 'housing-construction'
  | 'international-trade-investment'
  | 'provinces-territories-cities';

export interface SeriesMeta {
  id: string;
  title: string;
  source: SourceKind;
  sourceLabel: string;
  tableId?: string;
  vectorIds?: number[];
  valetGroup?: string;
  valetSeriesKey?: string;
  units: string;
  unitsDetail?: string;
  frequency: 'Daily' | 'Weekly' | 'Monthly' | 'Quarterly' | 'Annual';
  category: CategorySlug;
  description: string;
  featured?: boolean;
  lastVerified: string;
}

export interface CategoryMeta {
  slug: CategorySlug;
  title: string;
  blurb: string;
}

export const CATEGORIES: CategoryMeta[] = [
  { slug: 'money-banking-finance', title: 'Money, Banking and Finance', blurb: 'Policy rates, bond yields, money supply and the Canada-US exchange rate.' },
  { slug: 'population-employment-labour', title: 'Population, Employment and Labour', blurb: 'Jobs, wages, vacancies and employment insurance from national surveys.' },
  { slug: 'national-accounts', title: 'National Accounts', blurb: 'GDP, income and the current account from the macroeconomic accounts.' },
  { slug: 'production-business-activity', title: 'Production and Business Activity', blurb: 'What businesses make and sell: manufacturing, retail, wholesale and capacity use.' },
  { slug: 'prices', title: 'Prices', blurb: 'Consumer, producer and housing price indexes.' },
  { slug: 'housing-construction', title: 'Housing and Construction', blurb: 'Starts and building permits from CMHC and StatCan.' },
  { slug: 'international-trade-investment', title: 'International Trade and Investment', blurb: 'Merchandise exports, imports and the trade balance.' },
  { slug: 'provinces-territories-cities', title: 'Provinces, Territories and Cities', blurb: 'Provincial unemployment, prices and population.' },
];

const V = '2026-10-09';

export const SERIES: SeriesMeta[] = [
  // ---------- money, banking and finance ----------
  {
    id: 'POLICY_RATE',
    title: 'Bank of Canada Policy Interest Rate',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    valetGroup: 'ATABLE_POLICY_INSTRUMENT',
    valetSeriesKey: 'STATIC_ATABLE_V39079',
    units: 'Percent',
    unitsDetail: 'Target for the overnight rate, end of month',
    frequency: 'Monthly',
    category: 'money-banking-finance',
    description: 'The Bank of Canada target for the overnight rate, the benchmark that anchors prime rates and mortgage pricing across the economy.',
    featured: true,
    lastVerified: V,
  },
  {
    id: 'OVERNIGHT_RATE',
    title: 'Overnight Money Market Rate',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    valetGroup: 'ATABLE_POLICY_INSTRUMENT',
    valetSeriesKey: 'V122514',
    units: 'Percent',
    unitsDetail: 'Monthly average',
    frequency: 'Monthly',
    category: 'money-banking-finance',
    description: 'The actual rate at which major participants borrow and lend overnight funds, which the Bank steers toward its policy target.',
    lastVerified: V,
  },
  {
    id: 'CORRA',
    title: 'CORRA',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    valetGroup: 'CORRA',
    valetSeriesKey: 'AVG.INTWO',
    units: 'Percent',
    unitsDetail: 'Canadian Overnight Repo Rate Average, daily',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'The Canadian Overnight Repo Rate Average, the transaction-based risk-free reference rate for Canadian-dollar overnight funding.',
    lastVerified: V,
  },
  {
    id: 'BOND_2Y',
    title: '2-Year Government of Canada Bond Yield',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    valetGroup: 'bond_yields_benchmark',
    valetSeriesKey: 'BD.CDN.2YR.DQ.YLD',
    units: 'Percent',
    unitsDetail: 'Benchmark bond yield, daily',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'Yield on the 2-year Government of Canada benchmark bond, sensitive to near-term Bank of Canada policy expectations.',
    lastVerified: V,
  },
  {
    id: 'BOND_5Y',
    title: '5-Year Government of Canada Bond Yield',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    valetGroup: 'bond_yields_benchmark',
    valetSeriesKey: 'BD.CDN.5YR.DQ.YLD',
    units: 'Percent',
    unitsDetail: 'Benchmark bond yield, daily',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'Yield on the 5-year Government of Canada benchmark bond, the reference rate behind most fixed mortgage pricing in Canada.',
    lastVerified: V,
  },
  {
    id: 'BOND_10Y',
    title: '10-Year Government of Canada Bond Yield',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    valetGroup: 'bond_yields_benchmark',
    valetSeriesKey: 'BD.CDN.10YR.DQ.YLD',
    units: 'Percent',
    unitsDetail: 'Benchmark bond yield, daily',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'Yield on the 10-year Government of Canada benchmark bond, the standard gauge of long-term borrowing costs and growth expectations.',
    featured: true,
    lastVerified: V,
  },
  {
    id: 'TBILL_3M',
    title: '3-Month Treasury Bill Yield',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    valetGroup: 'MONEY_MARKET',
    valetSeriesKey: 'TB.CDN.90D.MID',
    units: 'Percent',
    unitsDetail: 'Money market yield, daily',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'Yield on 3-month Government of Canada treasury bills, the short-term risk-free rate used across money markets.',
    lastVerified: V,
  },
  {
    id: 'M2_PP',
    title: 'M2++ Money Supply',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Chartered Bank Assets and Liabilities',
    tableId: '10-10-0116-01',
    vectorIds: [41552801],
    units: 'Millions of dollars',
    unitsDetail: 'M2++ gross, month-end',
    frequency: 'Monthly',
    category: 'money-banking-finance',
    description: 'Broad money (M2++ gross): currency plus bank deposits and near-money holdings, the widest monthly gauge of money in the economy.',
    lastVerified: V,
  },
  {
    id: 'USDCAD',
    title: 'US Dollar / Canadian Dollar Exchange Rate',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    valetGroup: 'FX_RATES_DAILY',
    valetSeriesKey: 'FXUSDCAD',
    units: 'CAD per USD',
    unitsDetail: 'Daily average, indicative',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'Canadian dollars per US dollar from the Bank of Canada daily average noon series, the reference rate for trade and investment.',
    featured: true,
    lastVerified: V,
  },

  // ---------- population, employment and labour ----------
  {
    id: 'UNRATE_CA',
    title: 'Unemployment Rate',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    tableId: '14-10-0287-01',
    vectorIds: [2062815],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'Share of the labour force aged 15 and over without work but available and looking, the headline gauge of labour market slack.',
    featured: true,
    lastVerified: V,
  },
  {
    id: 'EMPLOYMENT_CA',
    title: 'Employment',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    tableId: '14-10-0287-01',
    vectorIds: [2062811],
    units: 'Thousands of persons',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'Number of employed people aged 15 and over, the level counterpart to the unemployment rate.',
    lastVerified: V,
  },
  {
    id: 'PARTRATE_CA',
    title: 'Labour Force Participation Rate',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    tableId: '14-10-0287-01',
    vectorIds: [2062816],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'Share of the population aged 15 and over that is working or looking for work, which separates job growth from demographic drag.',
    lastVerified: V,
  },
  {
    id: 'AVG_HOURLY_EARNINGS',
    title: 'Average Hourly Earnings',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Survey of Employment, Payrolls and Hours',
    tableId: '14-10-0205-01',
    vectorIds: [1592156],
    units: 'Dollars per hour',
    unitsDetail: 'Employees paid by the hour, including overtime',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'Average hourly pay including overtime for hourly employees, the payroll-based read on wage growth that feeds inflation analysis.',
    lastVerified: V,
  },
  {
    id: 'JOB_VACANCY_RATE',
    title: 'Job Vacancy Rate',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Job Vacancy and Wage Survey',
    tableId: '14-10-0371-01',
    vectorIds: [1212389365],
    units: 'Percent',
    unitsDetail: 'Monthly',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'Vacant positions as a share of all payroll jobs, the demand-side complement to the unemployment rate.',
    lastVerified: V,
  },
  {
    id: 'EI_BENEFICIARIES',
    title: 'Employment Insurance Beneficiaries',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Employment Insurance Statistics',
    tableId: '14-10-0009-01',
    vectorIds: [64540902],
    units: 'Persons',
    unitsDetail: 'All benefit types, monthly',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'People receiving employment insurance income benefits, a high-frequency count of insured joblessness.',
    lastVerified: V,
  },

  // ---------- national accounts ----------
  {
    id: 'GDP_REAL',
    title: 'Real Gross Domestic Product',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian System of Macroeconomic Accounts',
    tableId: '36-10-0104-01',
    vectorIds: [62305752],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'Inflation-adjusted value of all goods and services produced, the expenditure-based headline measure of economic growth.',
    featured: true,
    lastVerified: V,
  },
  {
    id: 'GDP_NOMINAL',
    title: 'Nominal Gross Domestic Product',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian System of Macroeconomic Accounts',
    tableId: '36-10-0104-01',
    vectorIds: [62305783],
    units: 'Millions of dollars',
    unitsDetail: 'Current prices, seasonally adjusted at annual rates',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'GDP in current dollars, which combines real growth and price change and anchors ratios like debt-to-GDP.',
    lastVerified: V,
  },
  {
    id: 'GDP_MONTHLY',
    title: 'Monthly GDP by Industry',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Gross Domestic Product by Industry',
    tableId: '36-10-0434-02',
    vectorIds: [65201210],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'All industries, seasonally adjusted at annual rates',
    frequency: 'Monthly',
    category: 'national-accounts',
    description: 'Monthly value-added across all industries, the earliest official read on each quarter of GDP growth.',
    lastVerified: V,
  },
  {
    id: 'GDP_PER_CAPITA',
    title: 'Real GDP per Capita',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian System of Macroeconomic Accounts',
    tableId: '36-10-0706-01',
    vectorIds: [1645315579],
    units: 'Chained 2017 dollars',
    unitsDetail: 'Quarterly',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'Inflation-adjusted output per person, which shows whether growth is outpacing population change.',
    lastVerified: V,
  },
  {
    id: 'DISP_INCOME_PC',
    title: 'Household Disposable Income per Capita',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian System of Macroeconomic Accounts',
    tableId: '36-10-0706-01',
    vectorIds: [1645315586],
    units: 'Dollars',
    unitsDetail: 'Current prices, quarterly',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'After-tax income per person, the national-accounts measure of what households have available to spend or save.',
    lastVerified: V,
  },
  {
    id: 'CURRENT_ACCOUNT',
    title: 'Current Account Balance',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Balance of International Payments',
    tableId: '36-10-0018-01',
    vectorIds: [61915304],
    units: 'Millions of dollars',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'Net balance on trade, investment income and transfers with the rest of the world; negative means Canada borrows from abroad.',
    lastVerified: V,
  },

  // ---------- production and business activity ----------
  {
    id: 'MFG_SALES_REAL',
    title: 'Real Manufacturing Sales',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Monthly Survey of Manufacturing',
    tableId: '16-10-0013-01',
    vectorIds: [123263908],
    units: 'Millions of 2017 dollars',
    unitsDetail: 'Shipments, monthly',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Price-adjusted value of goods shipped by manufacturers, the volume read on factory output.',
    lastVerified: V,
  },
  {
    id: 'RETAIL_SALES',
    title: 'Retail Sales',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Retail Trade Survey',
    tableId: '20-10-0056-01',
    vectorIds: [1446859483],
    units: 'Thousands of dollars',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Total monthly sales by retailers, the timeliest gauge of household goods spending.',
    lastVerified: V,
  },
  {
    id: 'WHOLESALE_SALES',
    title: 'Wholesale Sales',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Wholesale Trade Survey',
    tableId: '20-10-0074-01',
    vectorIds: [52367637],
    units: 'Thousands of dollars',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly sales by merchant wholesalers, the upstream read on goods flowing toward retailers.',
    lastVerified: V,
  },
  {
    id: 'CAP_UTILIZATION',
    title: 'Industrial Capacity Utilization Rate',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Industrial Capacity Utilization',
    tableId: '16-10-0109-01',
    vectorIds: [4331081],
    units: 'Percent',
    unitsDetail: 'Total industrial, quarterly',
    frequency: 'Quarterly',
    category: 'production-business-activity',
    description: 'Share of industrial capacity in use, which signals inflation pressure when factories run near their limits.',
    lastVerified: V,
  },

  // ---------- prices ----------
  {
    id: 'CPI_ALLITEMS_NSA',
    title: 'Consumer Price Index, All-items',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    tableId: '18-10-0004-01',
    vectorIds: [41690973],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'The all-items CPI level (2002=100); twelve-month change in this index is the inflation rate the Bank of Canada targets at 2%.',
    lastVerified: V,
  },
  {
    id: 'CPI_ALLITEMS_SA',
    title: 'Consumer Price Index, All-items (Seasonally Adjusted)',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    tableId: '18-10-0006-01',
    vectorIds: [41690914],
    units: 'Index, 2002=100',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'Seasonally adjusted all-items CPI, which strips regular seasonal moves to reveal underlying monthly inflation momentum.',
    featured: true,
    lastVerified: V,
  },
  {
    id: 'CPI_SHELTER_SA',
    title: 'CPI: Shelter',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    tableId: '18-10-0006-01',
    vectorIds: [41690916],
    units: 'Index, 2002=100',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'The shelter component of CPI, covering rent, owned accommodation and utilities, the largest weight in the inflation basket.',
    lastVerified: V,
  },
  {
    id: 'CPI_EXFOODENERGY_SA',
    title: 'CPI: All-items Excluding Food and Energy',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    tableId: '18-10-0006-01',
    vectorIds: [41690924],
    units: 'Index, 2002=100',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'CPI excluding food and energy, a core-inflation proxy that filters the two most volatile basket components.',
    lastVerified: V,
  },
  {
    id: 'IPPI',
    title: 'Industrial Product Price Index',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Industrial Product Price Index',
    tableId: '18-10-0265-01',
    vectorIds: [1230995983],
    units: 'Index',
    unitsDetail: 'Total, monthly',
    frequency: 'Monthly',
    category: 'prices',
    description: 'Prices manufacturers receive at the factory gate, a leading indicator of consumer-price pressure downstream.',
    lastVerified: V,
  },
  {
    id: 'NHPI',
    title: 'New Housing Price Index',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, New Housing Price Index',
    tableId: '18-10-0205-01',
    vectorIds: [111955442],
    units: 'Index',
    unitsDetail: 'Total house and land, monthly',
    frequency: 'Monthly',
    category: 'prices',
    description: 'Contract prices for new residential houses agreed between builders and buyers, the price signal from new construction.',
    lastVerified: V,
  },

  // ---------- housing and construction ----------
  {
    id: 'HOUSING_STARTS',
    title: 'Housing Starts',
    source: 'statcan',
    sourceLabel: 'Canada Mortgage and Housing Corporation via Statistics Canada',
    tableId: '34-10-0158-01',
    vectorIds: [52300157],
    units: 'Thousands of units',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Monthly',
    category: 'housing-construction',
    description: 'Annualized pace of new residential construction starts, the physical-quantity counterpart to housing price indexes.',
    lastVerified: V,
  },
  {
    id: 'BUILDING_PERMITS',
    title: 'Building Permits',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Building Permits Survey',
    tableId: '34-10-0292-01',
    vectorIds: [1675119645],
    units: 'Thousands of dollars',
    unitsDetail: 'Seasonally adjusted, current dollars',
    frequency: 'Monthly',
    category: 'housing-construction',
    description: 'Value of permits issued for residential and non-residential construction, a leading indicator of building intentions.',
    lastVerified: V,
  },

  // ---------- international trade and investment ----------
  {
    id: 'EXPORTS',
    title: 'Merchandise Exports',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian International Merchandise Trade',
    tableId: '12-10-0174-01',
    vectorIds: [1566934494],
    units: 'Thousands of dollars',
    unitsDetail: 'Customs-based, all countries, monthly',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'Total value of goods Canada sells abroad, customs-based and covering all trading partners.',
    lastVerified: V,
  },
  {
    id: 'IMPORTS',
    title: 'Merchandise Imports',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian International Merchandise Trade',
    tableId: '12-10-0174-01',
    vectorIds: [1566929544],
    units: 'Thousands of dollars',
    unitsDetail: 'Customs-based, all countries, monthly',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'Total value of goods Canada buys from abroad, customs-based and covering all trading partners.',
    lastVerified: V,
  },
  {
    id: 'TRADE_BALANCE',
    title: 'Merchandise Trade Balance',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian International Merchandise Trade',
    tableId: '12-10-0174-01',
    vectorIds: [1566934494, 1566929544],
    units: 'Thousands of dollars',
    unitsDetail: 'Exports minus imports, computed from the two series',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'Exports minus imports of merchandise; positive is a surplus. Computed from the verified exports and imports vectors above.',
    lastVerified: V,
  },

  // ---------- provinces, territories and cities ----------
  {
    id: 'UNRATE_QC',
    title: 'Unemployment Rate: Quebec',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    tableId: '14-10-0287-01',
    vectorIds: [2063760],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Quebec unemployment rate from the Labour Force Survey, for comparing provincial labour markets.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_ON',
    title: 'Unemployment Rate: Ontario',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    tableId: '14-10-0287-01',
    vectorIds: [2063949],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Ontario unemployment rate from the Labour Force Survey, for comparing provincial labour markets.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_AB',
    title: 'Unemployment Rate: Alberta',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    tableId: '14-10-0287-01',
    vectorIds: [2064516],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Alberta unemployment rate from the Labour Force Survey, for comparing provincial labour markets.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_BC',
    title: 'Unemployment Rate: British Columbia',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    tableId: '14-10-0287-01',
    vectorIds: [2064705],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'British Columbia unemployment rate from the Labour Force Survey, for comparing provincial labour markets.',
    lastVerified: V,
  },
  {
    id: 'CPI_QC',
    title: 'CPI: Quebec',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    tableId: '18-10-0004-01',
    vectorIds: [41691783],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Quebec all-items CPI, for comparing provincial inflation against the national index.',
    lastVerified: V,
  },
  {
    id: 'CPI_ON',
    title: 'CPI: Ontario',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    tableId: '18-10-0004-01',
    vectorIds: [41691919],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Ontario all-items CPI, for comparing provincial inflation against the national index.',
    lastVerified: V,
  },
  {
    id: 'CPI_AB',
    title: 'CPI: Alberta',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    tableId: '18-10-0004-01',
    vectorIds: [41692327],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Alberta all-items CPI, for comparing provincial inflation against the national index.',
    lastVerified: V,
  },
  {
    id: 'CPI_BC',
    title: 'CPI: British Columbia',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    tableId: '18-10-0004-01',
    vectorIds: [41692462],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'British Columbia all-items CPI, for comparing provincial inflation against the national index.',
    lastVerified: V,
  },
  {
    id: 'POPULATION',
    title: 'Population',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Population Estimates',
    tableId: '17-10-0009-01',
    vectorIds: [1],
    units: 'Persons',
    unitsDetail: 'Quarterly estimates',
    frequency: 'Quarterly',
    category: 'provinces-territories-cities',
    description: 'Quarterly estimated resident population of Canada, the denominator behind every per-capita series in this registry.',
    lastVerified: V,
  },
];

/* ---- Helpers expected by the app (derived from the verified SERIES list) ---- */

export const REGISTRY: SeriesMeta[] = SERIES;

export const CATEGORY_LABELS: Record<CategorySlug, string> = Object.fromEntries(
  CATEGORIES.map((c) => [c.slug, c.title])
) as Record<CategorySlug, string>;

export function getSeries(id: string): SeriesMeta | undefined {
  return SERIES.find((s) => s.id === id);
}

export function searchSeries(q: string): SeriesMeta[] {
  const needle = q.trim().toLowerCase();
  if (!needle) return SERIES;
  return SERIES.filter(
    (s) =>
      s.id.toLowerCase().includes(needle) ||
      s.title.toLowerCase().includes(needle) ||
      s.description.toLowerCase().includes(needle)
  );
}
