// CRED series registry. Every mapping below was verified live on 2026-10-09
// against Statistics Canada WDS or Bank of Canada Valet (see verification-report.md).
// LFS vectors (14-10-0287-01) were verified against StatCan's official full-table
// CSV for the 2026-09-04 release because WDS data endpoints return HTTP 409
// (table locked) for that survey during the nightly refresh window.

export type SourceKind = 'statcan' | 'boc';

export type CategorySlug =
  | 'money-banking-finance'
  | 'population-employment-labour'
  | 'national-accounts'
  | 'production-business-activity'
  | 'prices'
  | 'housing-construction'
  | 'international-trade-investment'
  | 'provinces-territories-cities';

export interface SeriesMeta {
  id: string;
  title: string;
  source: SourceKind;
  sourceLabel: string;
  tableId?: string;
  vectorIds?: number[];
  valetGroup?: string;
  valetSeriesKey?: string;
  units: string;
  unitsDetail?: string;
  frequency: 'Daily' | 'Weekly' | 'Monthly' | 'Quarterly' | 'Annual';
  category: CategorySlug;
  release: string;
  releaseUrl: string;
  sourceUrl: string;
  description: string;
  featured?: boolean;
  lastVerified: string;
  // Map view: series in the same geoFamily share a choropleth toggle.
  geoFamily?: 'unemployment-by-province' | 'cpi-by-province';
}

export interface CategoryMeta {
  slug: CategorySlug;
  title: string;
  blurb: string;
}

export const CATEGORIES: CategoryMeta[] = [
  { slug: 'money-banking-finance', title: 'Money, Banking and Finance', blurb: 'Policy rates, bond yields, money supply and the Canada-US exchange rate.' },
  { slug: 'population-employment-labour', title: 'Population, Employment and Labour', blurb: 'Jobs, wages, vacancies and employment insurance from national surveys.' },
  { slug: 'national-accounts', title: 'National Accounts', blurb: 'GDP, income and the current account from the macroeconomic accounts.' },
  { slug: 'production-business-activity', title: 'Production and Business Activity', blurb: 'What businesses make and sell: manufacturing, retail, wholesale and capacity use.' },
  { slug: 'prices', title: 'Prices', blurb: 'Consumer, producer and housing price indexes.' },
  { slug: 'housing-construction', title: 'Housing and Construction', blurb: 'Starts and building permits from CMHC and StatCan.' },
  { slug: 'international-trade-investment', title: 'International Trade and Investment', blurb: 'Merchandise exports, imports and the trade balance.' },
  { slug: 'provinces-territories-cities', title: 'Provinces, Territories and Cities', blurb: 'Provincial unemployment, prices and population.' },
];

const V = '2026-10-09';

export const SERIES: SeriesMeta[] = [
  // ---------- money, banking and finance ----------
  {
    id: 'POLICY_RATE',
    title: 'Bank of Canada Policy Interest Rate',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Policy interest rate',
    releaseUrl: 'https://www.bankofcanada.ca/core-functions/monetary-policy/key-interest-rate/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'ATABLE_POLICY_INSTRUMENT',
    valetSeriesKey: 'STATIC_ATABLE_V39079',
    units: 'Percent',
    unitsDetail: 'Target for the overnight rate, end of month',
    frequency: 'Monthly',
    category: 'money-banking-finance',
    description: 'The Bank of Canada\'s target for the overnight rate, the policy instrument set at each of the Bank\'s eight scheduled decision dates per year. It anchors the prime rates banks charge households and businesses, transmitting monetary policy through mortgages and business credit. This series carries the month-end target value.',
    featured: true,
    lastVerified: V,
  },
  {
    id: 'OVERNIGHT_RATE',
    title: 'Overnight Money Market Rate',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Money market rates',
    releaseUrl: 'https://www.bankofcanada.ca/valet/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'ATABLE_POLICY_INSTRUMENT',
    valetSeriesKey: 'V122514',
    units: 'Percent',
    unitsDetail: 'Monthly average',
    frequency: 'Monthly',
    category: 'money-banking-finance',
    description: 'The average rate at which major market participants actually borrow and lend funds overnight. The Bank of Canada steers this rate toward its policy target through its operating framework, so the gap between the two shows how tightly policy is transmitting. Published as a monthly average.',
    lastVerified: V,
  },
  {
    id: 'CORRA',
    title: 'CORRA',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Canadian Overnight Repo Rate Average',
    releaseUrl: 'https://www.bankofcanada.ca/valet/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'CORRA',
    valetSeriesKey: 'AVG.INTWO',
    units: 'Percent',
    unitsDetail: 'Canadian Overnight Repo Rate Average, daily',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'The Canadian Overnight Repo Rate Average, a transaction-based measure of the cost of overnight repo funding secured by Government of Canada securities. It serves as Canada\'s risk-free reference rate for Canadian-dollar derivatives and floating-rate products. Published daily by the Bank of Canada.',
    lastVerified: V,
  },
  {
    id: 'BOND_2Y',
    title: '2-Year Government of Canada Bond Yield',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Canadian bond yields',
    releaseUrl: 'https://www.bankofcanada.ca/rates/interest-rates/canadian-bonds/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'bond_yields_benchmark',
    valetSeriesKey: 'BD.CDN.2YR.DQ.YLD',
    units: 'Percent',
    unitsDetail: 'Benchmark bond yield, daily',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'The yield on the 2-year Government of Canada benchmark bond, the market\'s pricing of short-term sovereign borrowing. It moves closely with expectations for the Bank of Canada\'s policy rate over the next two years, making it the most policy-sensitive point on the yield curve. Published daily.',
    lastVerified: V,
  },
  {
    id: 'BOND_5Y',
    title: '5-Year Government of Canada Bond Yield',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Canadian bond yields',
    releaseUrl: 'https://www.bankofcanada.ca/rates/interest-rates/canadian-bonds/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'bond_yields_benchmark',
    valetSeriesKey: 'BD.CDN.5YR.DQ.YLD',
    units: 'Percent',
    unitsDetail: 'Benchmark bond yield, daily',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'The yield on the 5-year Government of Canada benchmark bond. Lenders price most Canadian fixed-rate mortgages off the 5-year GoC yield, so it is the market rate that most directly sets what households pay for a 5-year fixed mortgage. Published daily.',
    lastVerified: V,
  },
  {
    id: 'BOND_10Y',
    title: '10-Year Government of Canada Bond Yield',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Canadian bond yields',
    releaseUrl: 'https://www.bankofcanada.ca/rates/interest-rates/canadian-bonds/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'bond_yields_benchmark',
    valetSeriesKey: 'BD.CDN.10YR.DQ.YLD',
    units: 'Percent',
    unitsDetail: 'Benchmark bond yield, daily',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'The yield on the 10-year Government of Canada benchmark bond, the standard gauge of long-term sovereign borrowing costs. It embeds market expectations for growth and inflation over the coming decade and anchors pricing for long-term corporate debt. Published daily.',
    featured: true,
    lastVerified: V,
  },
  {
    id: 'TBILL_3M',
    title: '3-Month Treasury Bill Yield',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Treasury bill yields',
    releaseUrl: 'https://www.bankofcanada.ca/valet/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'MONEY_MARKET',
    valetSeriesKey: 'TB.CDN.90D.MID',
    units: 'Percent',
    unitsDetail: 'Money market yield, daily',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'The yield on 90-day Government of Canada treasury bills at the mid-market rate. T-bills are the shortest-term federal borrowing instrument, so this series is the purest daily read on the risk-free short rate outside the policy target itself. Published daily.',
    lastVerified: V,
  },
  {
    id: 'M2_PP',
    title: 'M2++ Money Supply',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Chartered Bank Assets and Liabilities',
    release: 'Chartered Bank Assets and Liabilities',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1010011601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1010011601',
    tableId: '10-10-0116-01',
    vectorIds: [41552801],
    units: 'Millions of dollars',
    unitsDetail: 'M2++ gross, month-end',
    frequency: 'Monthly',
    category: 'money-banking-finance',
    description: 'M2++ gross, the broadest monthly money aggregate: currency in circulation plus bank deposits, non-bank deposits and other near-money holdings. It measures the stock of liquid funds available to households and businesses at month-end, in millions of dollars. Sourced from chartered bank assets and liabilities data.',
    lastVerified: V,
  },
  {
    id: 'USDCAD',
    title: 'US Dollar / Canadian Dollar Exchange Rate',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Foreign exchange rates',
    releaseUrl: 'https://www.bankofcanada.ca/rates/exchange/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'FX_RATES_DAILY',
    valetSeriesKey: 'FXUSDCAD',
    units: 'CAD per USD',
    unitsDetail: 'Daily average, indicative',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'Canadian dollars per one US dollar, the Bank of Canada\'s daily average indicative rate. It is the reference rate for valuing cross-border trade and investment between Canada and its largest trading partner. A rising value means the Canadian dollar is weakening against the US dollar.',
    featured: true,
    lastVerified: V,
  },  {
    id: 'PRIME_RATE',
    title: 'Chartered Bank Prime Rate',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Chartered bank interest rates',
    releaseUrl: 'https://www.bankofcanada.ca/valet/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'CHARTERED_BANK_INTEREST',
    valetSeriesKey: 'V80691311',
    units: 'Percent',
    unitsDetail: 'Posted rate, weekly',
    frequency: 'Weekly',
    category: 'money-banking-finance',
    description: 'The prime rate posted by major chartered banks, published weekly by the Bank of Canada. It is the base rate for variable-rate mortgages and business loans: when the Bank of Canada moves its policy target, the chartered banks move prime in lockstep. This series carries the posted rate in percent.',
    lastVerified: V,
  },
  {
    id: 'MORTGAGE_5Y',
    title: 'Conventional 5-Year Mortgage Rate',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Chartered bank interest rates',
    releaseUrl: 'https://www.bankofcanada.ca/valet/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'CHARTERED_BANK_INTEREST',
    valetSeriesKey: 'V80691335',
    units: 'Percent',
    unitsDetail: 'Posted 5-year conventional rate, weekly',
    frequency: 'Weekly',
    category: 'money-banking-finance',
    description: 'The posted 5-year conventional mortgage rate at major chartered banks, published weekly. It is the benchmark behind fixed mortgage pricing; the negotiated rates borrowers actually pay typically run below the posted rate. Published in percent by the Bank of Canada.',
    lastVerified: V,
  },
  {
    id: 'FXEURCAD',
    title: 'Euro / Canadian Dollar Exchange Rate',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Foreign exchange rates',
    releaseUrl: 'https://www.bankofcanada.ca/rates/exchange/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'FX_RATES_DAILY',
    valetSeriesKey: 'FXEURCAD',
    units: 'CAD per EUR',
    unitsDetail: 'Daily average, indicative',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'Canadian dollars per euro from the Bank of Canada\'s daily foreign exchange series. It is the second most referenced Canadian-dollar cross after the US dollar, and the rate that matters for trade with the euro area. A rising value means the loonie is weakening against the euro.',
    lastVerified: V,
  },
  {
    id: 'BOND_LONG',
    title: 'Long-Term Government of Canada Bond Yield',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Canadian bond yields',
    releaseUrl: 'https://www.bankofcanada.ca/rates/interest-rates/canadian-bonds/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'bond_yields_benchmark',
    valetSeriesKey: 'BD.CDN.LONG.DQ.YLD',
    units: 'Percent',
    unitsDetail: 'Benchmark bond yield, daily',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'Yield on the long-term Government of Canada benchmark bond (over 10 years), published daily. It anchors pricing for pension funds and life insurers, whose long-dated liabilities are matched against long GoC yields. It moves with global long-rate trends as much as domestic policy.',
    lastVerified: V,
  },
  {
    id: 'CEER',
    title: 'Canadian Effective Exchange Rate Index',
    source: 'boc',
    sourceLabel: 'Bank of Canada, Valet',
    release: 'Canadian effective exchange rate',
    releaseUrl: 'https://www.bankofcanada.ca/rates/exchange/',
    sourceUrl: 'https://www.bankofcanada.ca/valet/',
    valetGroup: 'CEER_DAILY',
    valetSeriesKey: 'CEER_BROADN',
    units: 'Index',
    unitsDetail: 'Nominal, trade-weighted, daily',
    frequency: 'Daily',
    category: 'money-banking-finance',
    description: 'The Canadian Effective Exchange Rate index, a trade-weighted average of the loonie against the currencies of Canada\'s major trading partners. It rises when the Canadian dollar strengthens broadly rather than against a single currency. Published daily by the Bank of Canada on a nominal basis.',
    lastVerified: V,
  },

  // ---------- population, employment and labour ----------


  // ---------- population, employment and labour ----------
  {
    id: 'UNRATE_CA',
    geoFamily: 'unemployment-by-province',
    title: 'Unemployment Rate',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2062815],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'The share of the labour force aged 15 and over without work, available for work and actively looking, from the Labour Force Survey. It is the headline gauge of labour-market slack and the most watched monthly economic indicator in Canada. Seasonally adjusted; published monthly.',
    featured: true,
    lastVerified: V,
  },
  {
    id: 'EMPLOYMENT_CA',
    title: 'Employment',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2062811],
    units: 'Thousands of persons',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'The number of employed people aged 15 and over in Canada, in thousands of persons. It is the level counterpart to the unemployment rate: the rate can fall because people find jobs or because they stop looking, and this series tells the two apart. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'PARTRATE_CA',
    title: 'Labour Force Participation Rate',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2062816],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'The share of the population aged 15 and over that is either working or looking for work. It separates genuine job growth from demographic change: an aging population drags participation down even when hiring is strong. Seasonally adjusted; published monthly from the Labour Force Survey.',
    lastVerified: V,
  },
  {
    id: 'AVG_HOURLY_EARNINGS',
    title: 'Average Hourly Earnings',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Survey of Employment, Payrolls and Hours',
    release: 'Survey of Employment, Payrolls and Hours',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410020501',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410020501',
    tableId: '14-10-0205-01',
    vectorIds: [1592156],
    units: 'Dollars per hour',
    unitsDetail: 'Employees paid by the hour, including overtime',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'Average hourly earnings including overtime for employees paid by the hour, from the Survey of Employment, Payrolls and Hours. Because it comes from business payrolls rather than household interviews, it is the payroll-based read on wage growth that feeds into inflation analysis. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'JOB_VACANCY_RATE',
    title: 'Job Vacancy Rate',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Job Vacancy and Wage Survey',
    release: 'Job Vacancy and Wage Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410037101',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410037101',
    tableId: '14-10-0371-01',
    vectorIds: [1212389365],
    units: 'Percent',
    unitsDetail: 'Monthly',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'Vacant positions as a share of all occupied plus vacant payroll jobs, from the Job Vacancy and Wage Survey. It is the demand-side complement to the unemployment rate: high vacancies alongside low unemployment means workers hold bargaining power. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'EI_BENEFICIARIES',
    title: 'Employment Insurance Beneficiaries',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Employment Insurance Statistics',
    release: 'Employment Insurance Statistics',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410000901',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410000901',
    tableId: '14-10-0009-01',
    vectorIds: [64540902],
    units: 'Persons',
    unitsDetail: 'All benefit types, monthly',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'The number of people receiving Employment Insurance income benefits in the reference month. It is a high-frequency administrative count of insured joblessness that moves with layoffs rather than with job search. Published monthly from Employment Insurance Statistics.',
    lastVerified: V,
  },  {
    id: 'UNRATE_YOUTH',
    title: 'Youth Unemployment Rate',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2062842],
    units: 'Percent',
    unitsDetail: 'Ages 15 to 24, seasonally adjusted',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'The unemployment rate for 15-to-24-year-olds from the Labour Force Survey, in percent. Youth unemployment runs roughly double the national rate and moves first at turning points, since young workers are hired last and laid off first. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_MEN',
    title: 'Unemployment Rate: Men',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2062824],
    units: 'Percent',
    unitsDetail: 'Men, 15 years and over, seasonally adjusted',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'The unemployment rate for men aged 15 and over from the Labour Force Survey, in percent. Men are overrepresented in cyclical goods-producing industries like construction and manufacturing, so this series swings more with the business cycle. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_WOMEN',
    title: 'Unemployment Rate: Women',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2062833],
    units: 'Percent',
    unitsDetail: 'Women, 15 years and over, seasonally adjusted',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'The unemployment rate for women aged 15 and over from the Labour Force Survey, in percent. Women are overrepresented in services industries, which shed fewer jobs in downturns, so this series is typically less cyclical. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'EMPRATE_CA',
    title: 'Employment Rate',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2062817],
    units: 'Percent',
    unitsDetail: 'Total, 15 years and over, seasonally adjusted',
    frequency: 'Monthly',
    category: 'population-employment-labour',
    description: 'The employment rate: the share of the population aged 15 and over that is employed, in percent. It combines participation and unemployment into a single gauge, so it falls both when people lose jobs and when they stop looking. Seasonally adjusted; published monthly from the Labour Force Survey.',
    lastVerified: V,
  },

  // ---------- national accounts ----------


  // ---------- national accounts ----------
  {
    id: 'GDP_REAL',
    title: 'Real Gross Domestic Product',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian System of Macroeconomic Accounts',
    release: 'Canadian System of Macroeconomic Accounts',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401',
    tableId: '36-10-0104-01',
    vectorIds: [62305752],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'Inflation-adjusted gross domestic product in millions of chained 2017 dollars, the expenditure-based headline measure of economic growth. It answers whether the economy produced more than last quarter after removing price change. Seasonally adjusted at annual rates; published quarterly.',
    featured: true,
    lastVerified: V,
  },
  {
    id: 'GDP_NOMINAL',
    title: 'Nominal Gross Domestic Product',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian System of Macroeconomic Accounts',
    release: 'Canadian System of Macroeconomic Accounts',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401',
    tableId: '36-10-0104-01',
    vectorIds: [62305783],
    units: 'Millions of dollars',
    unitsDetail: 'Current prices, seasonally adjusted at annual rates',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'Gross domestic product in current dollars, combining real growth and price change, in millions of dollars. It anchors ratios like debt-to-GDP and measures the tax base, where what matters is dollars rather than volumes. Seasonally adjusted at annual rates; published quarterly.',
    lastVerified: V,
  },
  {
    id: 'GDP_MONTHLY',
    title: 'Monthly GDP by Industry',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Gross Domestic Product by Industry',
    release: 'Gross Domestic Product by Industry',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    tableId: '36-10-0434-02',
    vectorIds: [65201210],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'All industries, seasonally adjusted at annual rates',
    frequency: 'Monthly',
    category: 'national-accounts',
    description: 'Monthly value-added across all industries in millions of chained 2017 dollars, from the GDP by industry program. It is the earliest official read on each quarter of growth, published well before the quarterly expenditure accounts. Seasonally adjusted at annual rates.',
    lastVerified: V,
  },
  {
    id: 'GDP_PER_CAPITA',
    title: 'Real GDP per Capita',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian System of Macroeconomic Accounts',
    release: 'Canadian System of Macroeconomic Accounts',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610070601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610070601',
    tableId: '36-10-0706-01',
    vectorIds: [1645315579],
    units: 'Chained 2017 dollars',
    unitsDetail: 'Quarterly',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'Inflation-adjusted GDP per person in chained 2017 dollars. It shows whether the economy is producing more per Canadian, distinguishing genuine prosperity gains from growth that merely reflects a larger population. Published quarterly.',
    lastVerified: V,
  },
  {
    id: 'DISP_INCOME_PC',
    title: 'Household Disposable Income per Capita',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian System of Macroeconomic Accounts',
    release: 'Canadian System of Macroeconomic Accounts',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610070601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610070601',
    tableId: '36-10-0706-01',
    vectorIds: [1645315586],
    units: 'Dollars',
    unitsDetail: 'Current prices, quarterly',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'Household disposable income per person in current dollars: after-tax income available to spend or save. It is the national-accounts measure of household purchasing power, distinct from wages because it includes transfers and subtracts taxes. Published quarterly.',
    lastVerified: V,
  },
  {
    id: 'CURRENT_ACCOUNT',
    title: 'Current Account Balance',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Balance of International Payments',
    release: 'Canada\'s Balance of International Payments',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610001801',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610001801',
    tableId: '36-10-0018-01',
    vectorIds: [61915304],
    units: 'Millions of dollars',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'The net balance on trade in goods and services, investment income and transfers between Canada and the rest of the world, in millions of dollars. A negative balance means Canada as a whole is borrowing from abroad to fund its spending. Seasonally adjusted; published quarterly from the balance of international payments.',
    lastVerified: V,
  },  {
    id: 'CONS_HOUSEHOLD',
    title: 'Household Final Consumption Expenditure',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian System of Macroeconomic Accounts',
    release: 'Canadian System of Macroeconomic Accounts',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401',
    tableId: '36-10-0104-01',
    vectorIds: [62305724],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'Real household final consumption expenditure in millions of chained 2017 dollars, the largest GDP expenditure component at over half of output. It measures what households actually spend on goods and services after removing price change. Seasonally adjusted at annual rates; published quarterly.',
    lastVerified: V,
  },
  {
    id: 'INVEST_BUSINESS',
    title: 'Business Gross Fixed Capital Formation',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian System of Macroeconomic Accounts',
    release: 'Canadian System of Macroeconomic Accounts',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401',
    tableId: '36-10-0104-01',
    vectorIds: [62305733],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'Real business gross fixed capital formation in millions of chained 2017 dollars: investment in non-residential structures, machinery and equipment, and intellectual property. It is the capital-expenditure read on corporate confidence about future demand. Seasonally adjusted at annual rates; published quarterly.',
    lastVerified: V,
  },
  {
    id: 'CONS_GOVERNMENT',
    title: 'Government Final Consumption Expenditure',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian System of Macroeconomic Accounts',
    release: 'Canadian System of Macroeconomic Accounts',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401',
    tableId: '36-10-0104-01',
    vectorIds: [62305731],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'Real government final consumption expenditure in millions of chained 2017 dollars, covering services such as health, education and public administration. It is the steadiest GDP component, since public payrolls move less with the cycle than private spending. Seasonally adjusted at annual rates; published quarterly.',
    lastVerified: V,
  },
  {
    id: 'INVEST_RESIDENTIAL',
    title: 'Residential Structures Investment',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian System of Macroeconomic Accounts',
    release: 'Canadian System of Macroeconomic Accounts',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401',
    tableId: '36-10-0104-01',
    vectorIds: [62305734],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Quarterly',
    category: 'national-accounts',
    description: 'Real investment in residential structures in millions of chained 2017 dollars: new homes plus renovations. It is the national-accounts counterpart to housing starts, measured in dollars rather than units. Seasonally adjusted at annual rates; published quarterly.',
    lastVerified: V,
  },

  // ---------- production and business activity ----------


  // ---------- production and business activity ----------
  {
    id: 'MFG_SALES_REAL',
    title: 'Real Manufacturing Sales',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Monthly Survey of Manufacturing',
    release: 'Monthly Survey of Manufacturing',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1610001301',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1610001301',
    tableId: '16-10-0013-01',
    vectorIds: [123263908],
    units: 'Millions of 2017 dollars',
    unitsDetail: 'Shipments, monthly',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Price-adjusted value of goods shipped by Canadian manufacturers, in millions of 2017 dollars. It is the volume read on factory output, separating how much was made from what it sold for. Published monthly from the Monthly Survey of Manufacturing.',
    lastVerified: V,
  },
  {
    id: 'RETAIL_SALES',
    title: 'Retail Sales',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Retail Trade Survey',
    release: 'Retail Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010005601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010005601',
    tableId: '20-10-0056-01',
    vectorIds: [1446859483],
    units: 'Thousands of dollars',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Total monthly sales by Canadian retailers in thousands of dollars, the timeliest gauge of household spending on goods. It covers store and non-store retailers and moves closely with consumer confidence. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'WHOLESALE_SALES',
    title: 'Wholesale Sales',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Wholesale Trade Survey',
    release: 'Wholesale Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010007401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010007401',
    tableId: '20-10-0074-01',
    vectorIds: [52367637],
    units: 'Thousands of dollars',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly sales by merchant wholesalers in thousands of dollars, the upstream read on goods flowing from manufacturers toward retailers. Wholesale sales together with inventories signal where the goods pipeline is building or draining. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'CAP_UTILIZATION',
    title: 'Industrial Capacity Utilization Rate',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Industrial Capacity Utilization',
    release: 'Industrial Capacity Utilization Rates',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1610010901',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1610010901',
    tableId: '16-10-0109-01',
    vectorIds: [4331081],
    units: 'Percent',
    unitsDetail: 'Total industrial, quarterly',
    frequency: 'Quarterly',
    category: 'production-business-activity',
    description: 'The share of industrial capacity in use across Canadian industries, in percent. When factories run near their limits, bottlenecks push prices up, so this series is watched as an early signal of inflation pressure. Published quarterly.',
    lastVerified: V,
  },  {
    id: 'GDP_MFG',
    title: 'GDP: Manufacturing',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Gross Domestic Product by Industry',
    release: 'Gross Domestic Product by Industry',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    tableId: '36-10-0434-02',
    vectorIds: [65201263],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly value-added of the manufacturing sector in millions of chained 2017 dollars. Manufacturing is the largest goods-producing industry, so its path drives much of the monthly GDP swing. Seasonally adjusted at annual rates.',
    lastVerified: V,
  },
  {
    id: 'GDP_CONSTRUCTION',
    title: 'GDP: Construction',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Gross Domestic Product by Industry',
    release: 'Gross Domestic Product by Industry',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    tableId: '36-10-0434-02',
    vectorIds: [65201258],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly value-added of the construction sector in millions of chained 2017 dollars. It moves with housing and infrastructure cycles, rising when building investment is strong. Seasonally adjusted at annual rates.',
    lastVerified: V,
  },
  {
    id: 'GDP_WHOLESALE',
    title: 'GDP: Wholesale Trade',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Gross Domestic Product by Industry',
    release: 'Gross Domestic Product by Industry',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    tableId: '36-10-0434-02',
    vectorIds: [65201358],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly value-added of wholesale trade in millions of chained 2017 dollars. Wholesalers earn margins moving goods from producers to retailers, so this series tracks the health of the distribution layer. Seasonally adjusted at annual rates.',
    lastVerified: V,
  },
  {
    id: 'GDP_RETAIL',
    title: 'GDP: Retail Trade',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Gross Domestic Product by Industry',
    release: 'Gross Domestic Product by Industry',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    tableId: '36-10-0434-02',
    vectorIds: [65201368],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly value-added of retail trade in millions of chained 2017 dollars. This is the sector\'s contribution to GDP, distinct from retail sales: sales measure turnover, value-added measures the margin retailers keep. Seasonally adjusted at annual rates.',
    lastVerified: V,
  },
  {
    id: 'GDP_MINING_OILGAS',
    title: 'GDP: Mining, Quarrying, and Oil and Gas Extraction',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Gross Domestic Product by Industry',
    release: 'Gross Domestic Product by Industry',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    tableId: '36-10-0434-02',
    vectorIds: [65201236],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly value-added of mining, quarrying and oil and gas extraction in millions of chained 2017 dollars, including oil sands production. It is the most commodity-price-sensitive slice of GDP, swinging with global energy and metals markets. Seasonally adjusted at annual rates.',
    lastVerified: V,
  },
  {
    id: 'GDP_FINANCE',
    title: 'GDP: Finance and Insurance',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Gross Domestic Product by Industry',
    release: 'Gross Domestic Product by Industry',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    tableId: '36-10-0434-02',
    vectorIds: [65201407],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly value-added of finance and insurance in millions of chained 2017 dollars, covering banks, insurers and funds. It is one of the largest service industries in the economy and moves with credit growth and asset prices. Seasonally adjusted at annual rates.',
    lastVerified: V,
  },
  {
    id: 'GDP_PROF_SERVICES',
    title: 'GDP: Professional, Scientific and Technical Services',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Gross Domestic Product by Industry',
    release: 'Gross Domestic Product by Industry',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    tableId: '36-10-0434-02',
    vectorIds: [65201429],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly value-added of professional, scientific and technical services in millions of chained 2017 dollars, covering engineering, legal, consulting and computer services. It measures the output of the knowledge-intensive business services sector. Seasonally adjusted at annual rates.',
    lastVerified: V,
  },
  {
    id: 'GDP_REALESTATE',
    title: 'GDP: Real Estate and Rental and Leasing',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Gross Domestic Product by Industry',
    release: 'Gross Domestic Product by Industry',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043402',
    tableId: '36-10-0434-02',
    vectorIds: [65201419],
    units: 'Millions of chained 2017 dollars',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly value-added of real estate and rental and leasing in millions of chained 2017 dollars. It is dominated by imputed rent on owner-occupied housing: the national accounts treat homeowners as renting to themselves. Seasonally adjusted at annual rates.',
    lastVerified: V,
  },
  {
    id: 'RETAIL_MOTOR_VEHICLES',
    title: 'Retail Sales: Motor Vehicle and Parts Dealers',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Retail Trade Survey',
    release: 'Retail Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010005601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010005601',
    tableId: '20-10-0056-01',
    vectorIds: [1446859486],
    units: 'Thousands of dollars',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly sales at motor vehicle and parts dealers in thousands of dollars, seasonally adjusted. Autos are the most cyclical retail category: big-ticket, credit-sensitive purchases that households postpone in downturns. From the Retail Trade Survey.',
    lastVerified: V,
  },
  {
    id: 'RETAIL_FOOD_BEVERAGE',
    title: 'Retail Sales: Food and Beverage Retailers',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Retail Trade Survey',
    release: 'Retail Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010005601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010005601',
    tableId: '20-10-0056-01',
    vectorIds: [1446859500],
    units: 'Thousands of dollars',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly sales at food and beverage retailers in thousands of dollars, seasonally adjusted, covering grocery, convenience and liquor stores. Food spending barely moves with the cycle, so this series is the non-cyclical core of retail. From the Retail Trade Survey.',
    lastVerified: V,
  },
  {
    id: 'RETAIL_GASOLINE',
    title: 'Retail Sales: Gasoline Stations and Fuel Vendors',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Retail Trade Survey',
    release: 'Retail Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010005601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010005601',
    tableId: '20-10-0056-01',
    vectorIds: [1446859526],
    units: 'Thousands of dollars',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly sales at gasoline stations and fuel vendors in thousands of dollars, seasonally adjusted. These sales move mostly with pump prices rather than litres sold, so spikes here usually mean expensive fuel, not more driving. From the Retail Trade Survey.',
    lastVerified: V,
  },
  {
    id: 'RETAIL_ECOMMERCE',
    title: 'Retail E-commerce Sales',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Retail Trade Survey',
    release: 'Retail Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010005601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010005601',
    tableId: '20-10-0056-01',
    vectorIds: [1446859484],
    units: 'Thousands of dollars',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'production-business-activity',
    description: 'Monthly online sales by Canadian retailers in thousands of dollars, seasonally adjusted. It is the structural-shift gauge of retail: the share of spending moving from stores to screens. From the Retail Trade Survey.',
    lastVerified: V,
  },

  // ---------- prices ----------


  // ---------- prices ----------
  {
    id: 'CPI_ALLITEMS_NSA',
    geoFamily: 'cpi-by-province',
    title: 'Consumer Price Index, All-items',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41690973],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'The all-items Consumer Price Index level on a 2002=100 base, not seasonally adjusted. The twelve-month percent change in this index is the inflation rate the Bank of Canada targets at 2 percent. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_ALLITEMS_SA',
    title: 'Consumer Price Index, All-items (Seasonally Adjusted)',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000601',
    tableId: '18-10-0006-01',
    vectorIds: [41690914],
    units: 'Index, 2002=100',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'The seasonally adjusted all-items Consumer Price Index on a 2002=100 base. Seasonal adjustment strips regular calendar effects such as winter heating and holiday pricing, revealing underlying monthly inflation momentum. Published monthly.',
    featured: true,
    lastVerified: V,
  },
  {
    id: 'CPI_SHELTER_SA',
    title: 'CPI: Shelter',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000601',
    tableId: '18-10-0006-01',
    vectorIds: [41690916],
    units: 'Index, 2002=100',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'The shelter component of the Consumer Price Index, covering rent, owned accommodation and utilities, on a 2002=100 base. Shelter carries the largest weight in the CPI basket, so its path dominates headline inflation in housing-driven cycles. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_EXFOODENERGY_SA',
    title: 'CPI: All-items Excluding Food and Energy',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000601',
    tableId: '18-10-0006-01',
    vectorIds: [41690924],
    units: 'Index, 2002=100',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'The Consumer Price Index excluding food and energy, on a 2002=100 base. Removing the two most volatile basket components gives a proxy for core inflation that is less noisy month to month. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'IPPI',
    title: 'Industrial Product Price Index',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Industrial Product Price Index',
    release: 'Industrial Product Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810026501',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810026501',
    tableId: '18-10-0265-01',
    vectorIds: [1230995983],
    units: 'Index',
    unitsDetail: 'Total, monthly',
    frequency: 'Monthly',
    category: 'prices',
    description: 'The Industrial Product Price Index measures prices manufacturers receive at the factory gate. Because factory-gate prices feed through to consumer prices with a lag, it is a leading indicator of downstream inflation pressure. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'NHPI',
    title: 'New Housing Price Index',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, New Housing Price Index',
    release: 'New Housing Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810020501',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810020501',
    tableId: '18-10-0205-01',
    vectorIds: [111955442],
    units: 'Index',
    unitsDetail: 'Total house and land, monthly',
    frequency: 'Monthly',
    category: 'prices',
    description: 'The New Housing Price Index tracks contract prices for new residential houses as agreed between builders and buyers, split into house and land components. It is the price signal coming from new construction rather than resales. Published monthly.',
    lastVerified: V,
  },  {
    id: 'CPI_MEDIAN',
    title: 'CPI-median (Bank of Canada Core)',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index (Bank of Canada core measures)',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810025601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810025601',
    tableId: '18-10-0256-01',
    vectorIds: [1481215115],
    units: 'Index, January 1989=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'CPI-median, the Bank of Canada\'s preferred core inflation measure, indexed to January 1989=100. Each month it takes the weighted median of price changes across the CPI basket, filtering out extreme moves in either direction. Published monthly, not seasonally adjusted.',
    lastVerified: V,
  },
  {
    id: 'CPI_TRIM',
    title: 'CPI-trim (Bank of Canada Core)',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index (Bank of Canada core measures)',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810025601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810025601',
    tableId: '18-10-0256-01',
    vectorIds: [1481215116],
    units: 'Index, January 1989=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'CPI-trim, the Bank of Canada\'s trimmed-mean core inflation measure, indexed to January 1989=100. It drops the most extreme price changes from both tails of the basket each month, keeping the middle of the distribution. Published monthly, not seasonally adjusted.',
    lastVerified: V,
  },
  {
    id: 'CPI_ENERGY',
    title: 'CPI: Energy',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41691239],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'The energy component of the Consumer Price Index on a 2002=100 base, covering household electricity, natural gas, fuel oil and gasoline. Energy is the most volatile CPI component and drives most headline inflation swings. Published monthly, not seasonally adjusted.',
    lastVerified: V,
  },
  {
    id: 'CPI_GASOLINE',
    title: 'CPI: Gasoline',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41691136],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'Retail gasoline prices on a 2002=100 base, the most frequently observed price in the CPI basket. Because gasoline prices swing with crude oil, this component adds most of the month-to-month noise in headline inflation. Published monthly, not seasonally adjusted.',
    lastVerified: V,
  },
  {
    id: 'CPI_RENT',
    title: 'CPI: Rent',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41691052],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'The rent component of the Consumer Price Index on a 2002=100 base, measuring rents paid by tenants. It is the largest measured piece of shelter costs and moves slowly, since leases reset gradually. Published monthly, not seasonally adjusted.',
    lastVerified: V,
  },
  {
    id: 'CPI_SERVICES',
    title: 'CPI: Services',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41691230],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'The services half of the Consumer Price Index on a 2002=100 base. Services inflation runs stickier than goods inflation because it reflects wages more than import prices, which is why the Bank of Canada watches it closely. Published monthly, not seasonally adjusted.',
    lastVerified: V,
  },
  {
    id: 'CPI_FOOD_SA',
    title: 'CPI: Food (Seasonally Adjusted)',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000601',
    tableId: '18-10-0006-01',
    vectorIds: [41690915],
    units: 'Index, 2002=100',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'Seasonally adjusted food prices on a 2002=100 base, covering groceries and restaurant meals. Food is the basket component households notice most at the till. Seasonal adjustment removes regular harvest and holiday patterns to show underlying momentum. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_TRANSPORT_SA',
    title: 'CPI: Transportation (Seasonally Adjusted)',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000601',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000601',
    tableId: '18-10-0006-01',
    vectorIds: [41690919],
    units: 'Index, 2002=100',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'prices',
    description: 'Seasonally adjusted transportation costs on a 2002=100 base, covering vehicles, gasoline, insurance and airfares. It is the CPI component most exposed to both energy prices and supply-chain conditions. Published monthly.',
    lastVerified: V,
  },

  // ---------- housing and construction ----------


  // ---------- housing and construction ----------
  {
    id: 'HOUSING_STARTS',
    title: 'Housing Starts',
    source: 'statcan',
    sourceLabel: 'Canada Mortgage and Housing Corporation via Statistics Canada',
    release: 'Canada Mortgage and Housing Corporation',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410015801',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410015801',
    tableId: '34-10-0158-01',
    vectorIds: [52300157],
    units: 'Thousands of units',
    unitsDetail: 'Seasonally adjusted at annual rates',
    frequency: 'Monthly',
    category: 'housing-construction',
    description: 'The annualized pace of new residential construction starts in Canada, in thousands of units, collected by Canada Mortgage and Housing Corporation and distributed through Statistics Canada. It is the physical-quantity counterpart to housing price indexes: prices say what homes cost, starts say how many are being built. Seasonally adjusted at annual rates; published monthly.',
    lastVerified: V,
  },
  {
    id: 'BUILDING_PERMITS',
    title: 'Building Permits',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Building Permits Survey',
    release: 'Building Permits Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029201',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029201',
    tableId: '34-10-0292-01',
    vectorIds: [1675119645],
    units: 'Thousands of dollars',
    unitsDetail: 'Seasonally adjusted, current dollars',
    frequency: 'Monthly',
    category: 'housing-construction',
    description: 'The value of building permits issued by Canadian municipalities for residential and non-residential construction, in thousands of current dollars. Permits are filed before ground breaks, so this series leads actual construction activity by several months. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },  {
    id: 'INV_BUILDING_TOTAL',
    title: 'Investment in Building Construction',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Investment in Building Construction',
    release: 'Investment in Building Construction',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029301',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029301',
    tableId: '34-10-0293-01',
    vectorIds: [1705315926],
    units: 'Dollars',
    unitsDetail: 'Seasonally adjusted, current dollars',
    frequency: 'Monthly',
    category: 'housing-construction',
    description: 'The seasonally adjusted dollar value of all building construction put in place each month, in current dollars. It covers residential and non-residential buildings and is the monthly read on construction activity from permits to completions. From the Investment in Building Construction survey.',
    lastVerified: V,
  },
  {
    id: 'INV_BUILDING_RES',
    title: 'Investment in Residential Building Construction',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Investment in Building Construction',
    release: 'Investment in Building Construction',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029301',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029301',
    tableId: '34-10-0293-01',
    vectorIds: [1705315946],
    units: 'Dollars',
    unitsDetail: 'Seasonally adjusted, current dollars',
    frequency: 'Monthly',
    category: 'housing-construction',
    description: 'The seasonally adjusted dollar value of residential building construction put in place, in current dollars, covering single and multiple dwellings. It is the housing-cycle component of building investment, moving with starts and renovation demand. From the Investment in Building Construction survey.',
    lastVerified: V,
  },
  {
    id: 'INV_BUILDING_NONRES',
    title: 'Investment in Non-residential Building Construction',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Investment in Building Construction',
    release: 'Investment in Building Construction',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029301',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029301',
    tableId: '34-10-0293-01',
    vectorIds: [1705316166],
    units: 'Dollars',
    unitsDetail: 'Seasonally adjusted, current dollars',
    frequency: 'Monthly',
    category: 'housing-construction',
    description: 'The seasonally adjusted dollar value of non-residential building construction put in place, in current dollars, covering industrial, commercial, institutional and governmental buildings. It tracks business-cycle investment in structures rather than housing. From the Investment in Building Construction survey.',
    lastVerified: V,
  },
  {
    id: 'INV_BUILDING_SINGLE',
    title: 'Investment in Single-dwelling Construction',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Investment in Building Construction',
    release: 'Investment in Building Construction',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029301',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029301',
    tableId: '34-10-0293-01',
    vectorIds: [1705315966],
    units: 'Dollars',
    unitsDetail: 'Seasonally adjusted, current dollars',
    frequency: 'Monthly',
    category: 'housing-construction',
    description: 'The seasonally adjusted dollar value of single-dwelling construction put in place, in current dollars, covering singles, cottages and mobile homes. It is the low-density slice of residential investment. From the Investment in Building Construction survey.',
    lastVerified: V,
  },
  {
    id: 'INV_BUILDING_MULTI',
    title: 'Investment in Multi-dwelling Construction',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Investment in Building Construction',
    release: 'Investment in Building Construction',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029301',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410029301',
    tableId: '34-10-0293-01',
    vectorIds: [1705316066],
    units: 'Dollars',
    unitsDetail: 'Seasonally adjusted, current dollars',
    frequency: 'Monthly',
    category: 'housing-construction',
    description: 'The seasonally adjusted dollar value of multiple-dwelling construction put in place, in current dollars, covering doubles, rows and apartments. It tracks the shift toward denser housing supply in Canadian cities. From the Investment in Building Construction survey.',
    lastVerified: V,
  },
  {
    id: 'RENT_VACANCY',
    title: 'Rental Vacancy Rate',
    source: 'statcan',
    sourceLabel: 'Canada Mortgage and Housing Corporation via Statistics Canada',
    release: 'Rental Market Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410012701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410012701',
    tableId: '34-10-0127-01',
    vectorIds: [733334],
    units: 'Percent',
    unitsDetail: 'Apartment structures of 6+ units, CMAs, annual',
    frequency: 'Annual',
    category: 'housing-construction',
    description: 'The share of purpose-built rental apartments sitting vacant across census metropolitan areas, in percent, from the CMHC Rental Market Survey. It is the tightness gauge of the rental market: low vacancy means landlords hold pricing power. Published annually for apartment structures of six or more units.',
    lastVerified: V,
  },

  // ---------- international trade and investment ----------


  // ---------- international trade and investment ----------
  {
    id: 'EXPORTS',
    title: 'Merchandise Exports',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian International Merchandise Trade',
    release: 'Canadian International Merchandise Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210017401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210017401',
    tableId: '12-10-0174-01',
    vectorIds: [1566934494],
    units: 'Thousands of dollars',
    unitsDetail: 'Customs-based, all countries, monthly',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'The total customs-based value of merchandise Canada sells abroad, in thousands of dollars, covering all trading partners. It is the goods side of the trade ledger; services trade is measured separately. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'IMPORTS',
    title: 'Merchandise Imports',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian International Merchandise Trade',
    release: 'Canadian International Merchandise Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210017401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210017401',
    tableId: '12-10-0174-01',
    vectorIds: [1566929544],
    units: 'Thousands of dollars',
    unitsDetail: 'Customs-based, all countries, monthly',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'The total customs-based value of merchandise Canada buys from abroad, in thousands of dollars, covering all trading partners. Together with exports it determines the merchandise trade balance. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'TRADE_BALANCE',
    title: 'Merchandise Trade Balance',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian International Merchandise Trade',
    release: 'Canadian International Merchandise Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210017401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210017401',
    tableId: '12-10-0174-01',
    vectorIds: [1566934494, 1566929544],
    units: 'Thousands of dollars',
    unitsDetail: 'Exports minus imports, computed from the two series',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'Merchandise exports minus merchandise imports in thousands of dollars; a positive value is a trade surplus. It is computed from the two verified vectors above rather than fetched as a separate series, so it always matches the exports and imports shown here. Published monthly.',
    lastVerified: V,
  },  {
    id: 'EXPORTS_US',
    title: 'Merchandise Exports to the United States',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian International Merchandise Trade',
    release: 'Canadian International Merchandise Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210001101',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210001101',
    tableId: '12-10-0011-01',
    vectorIds: [87008898],
    units: 'Millions of dollars',
    unitsDetail: 'Customs-based, seasonally adjusted',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'Customs-based merchandise exports to the United States in millions of dollars, seasonally adjusted. The US takes roughly three-quarters of Canada\'s goods exports, so this bilateral flow dominates the trade balance. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'IMPORTS_US',
    title: 'Merchandise Imports from the United States',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian International Merchandise Trade',
    release: 'Canadian International Merchandise Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210001101',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210001101',
    tableId: '12-10-0011-01',
    vectorIds: [87008782],
    units: 'Millions of dollars',
    unitsDetail: 'Customs-based, seasonally adjusted',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'Customs-based merchandise imports from the United States in millions of dollars, seasonally adjusted. The US is Canada\'s largest source of imported goods, reflecting integrated North American supply chains. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'TRADE_BALANCE_US',
    title: 'Canada-US Merchandise Trade Balance',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian International Merchandise Trade',
    release: 'Canadian International Merchandise Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210001101',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210001101',
    tableId: '12-10-0011-01',
    vectorIds: [87008898, 87008782],
    units: 'Millions of dollars',
    unitsDetail: 'Exports minus imports, computed from the two series',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'Merchandise exports minus imports with the United States in millions of dollars; positive is a surplus. It is computed from the two verified bilateral vectors above rather than fetched separately, so it always matches them. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'EXPORTS_CHINA',
    title: 'Merchandise Exports to China',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian International Merchandise Trade',
    release: 'Canadian International Merchandise Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210001101',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210001101',
    tableId: '12-10-0011-01',
    vectorIds: [87008907],
    units: 'Millions of dollars',
    unitsDetail: 'Customs-based, seasonally adjusted',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'Customs-based merchandise exports to China in millions of dollars, seasonally adjusted. China is Canada\'s second-largest merchandise export market. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'EXPORTS_EU',
    title: 'Merchandise Exports to the European Union',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Canadian International Merchandise Trade',
    release: 'Canadian International Merchandise Trade',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210001101',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210001101',
    tableId: '12-10-0011-01',
    vectorIds: [87008899],
    units: 'Millions of dollars',
    unitsDetail: 'Customs-based, seasonally adjusted',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'Customs-based merchandise exports to the European Union in millions of dollars, seasonally adjusted. It is the diversification read on Canadian export markets beyond the United States. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'SERVICES_EXPORTS',
    title: 'Services Exports',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, International Trade in Services',
    release: 'Canada\'s International Trade in Services',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210014401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210014401',
    tableId: '12-10-0144-01',
    vectorIds: [1105277795],
    units: 'Millions of dollars',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'Receipts for services sold abroad in millions of dollars, seasonally adjusted, covering commercial, travel, transportation and government services. Services trade is measured separately from the better-known merchandise trade. Published monthly from Canada\'s international trade in services.',
    lastVerified: V,
  },
  {
    id: 'SERVICES_IMPORTS',
    title: 'Services Imports',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, International Trade in Services',
    release: 'Canada\'s International Trade in Services',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210014401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210014401',
    tableId: '12-10-0144-01',
    vectorIds: [1105277805],
    units: 'Millions of dollars',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'Payments for services bought from abroad in millions of dollars, seasonally adjusted, covering commercial, travel, transportation and government services. Canadians\' spending on foreign travel is a large part of this flow. Published monthly from Canada\'s international trade in services.',
    lastVerified: V,
  },
  {
    id: 'SERVICES_BALANCE',
    title: 'Services Trade Balance',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, International Trade in Services',
    release: 'Canada\'s International Trade in Services',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210014401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210014401',
    tableId: '12-10-0144-01',
    vectorIds: [1105277815],
    units: 'Millions of dollars',
    unitsDetail: 'Receipts minus payments',
    frequency: 'Monthly',
    category: 'international-trade-investment',
    description: 'Services receipts minus payments in millions of dollars; the balance runs near zero, far smaller than the merchandise balance. It shows Canada roughly breaks even on services trade while merchandise drives the overall balance. Published monthly.',
    lastVerified: V,
  },

  // ---------- provinces, territories and cities ----------


  // ---------- provinces, territories and cities ----------
  {
    id: 'UNRATE_QC',
    geoFamily: 'unemployment-by-province',
    title: 'Unemployment Rate: Quebec',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2063760],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'The unemployment rate for Quebec from the Labour Force Survey, in percent. Provincial rates let you compare labour-market tightness across the four largest provinces instead of reading Canada as a single market. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_ON',
    geoFamily: 'unemployment-by-province',
    title: 'Unemployment Rate: Ontario',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2063949],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'The unemployment rate for Ontario from the Labour Force Survey, in percent. Provincial rates let you compare labour-market tightness across the four largest provinces instead of reading Canada as a single market. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_AB',
    geoFamily: 'unemployment-by-province',
    title: 'Unemployment Rate: Alberta',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2064516],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'The unemployment rate for Alberta from the Labour Force Survey, in percent. Provincial rates let you compare labour-market tightness across the four largest provinces instead of reading Canada as a single market. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_BC',
    geoFamily: 'unemployment-by-province',
    title: 'Unemployment Rate: British Columbia',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2064705],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'The unemployment rate for British Columbia from the Labour Force Survey, in percent. Provincial rates let you compare labour-market tightness across the four largest provinces instead of reading Canada as a single market. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_QC',
    geoFamily: 'cpi-by-province',
    title: 'CPI: Quebec',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41691783],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'The all-items Consumer Price Index for Quebec on a 2002=100 base, not seasonally adjusted. Provincial CPIs reveal where inflation is running hotter or cooler than the national average. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_ON',
    geoFamily: 'cpi-by-province',
    title: 'CPI: Ontario',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41691919],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'The all-items Consumer Price Index for Ontario on a 2002=100 base, not seasonally adjusted. Provincial CPIs reveal where inflation is running hotter or cooler than the national average. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_AB',
    geoFamily: 'cpi-by-province',
    title: 'CPI: Alberta',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41692327],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'The all-items Consumer Price Index for Alberta on a 2002=100 base, not seasonally adjusted. Provincial CPIs reveal where inflation is running hotter or cooler than the national average. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_BC',
    geoFamily: 'cpi-by-province',
    title: 'CPI: British Columbia',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41692462],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'The all-items Consumer Price Index for British Columbia on a 2002=100 base, not seasonally adjusted. Provincial CPIs reveal where inflation is running hotter or cooler than the national average. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'POPULATION',
    title: 'Population',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Population Estimates',
    release: 'Population Estimates',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710000901',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710000901',
    tableId: '17-10-0009-01',
    vectorIds: [1],
    units: 'Persons',
    unitsDetail: 'Quarterly estimates',
    frequency: 'Quarterly',
    category: 'provinces-territories-cities',
    description: 'Statistics Canada\'s quarterly estimated resident population of Canada, in persons. It is the denominator behind every per-capita series in this registry, from GDP per capita to disposable income per person. Published quarterly.',
    lastVerified: V,
  },  {
    id: 'UNRATE_MB',
    geoFamily: 'unemployment-by-province',
    title: 'Unemployment Rate: Manitoba',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2064138],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Manitoba unemployment rate from the Labour Force Survey, in percent. Provincial rates let you compare labour-market tightness across provinces instead of reading Canada as a single market. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_SK',
    geoFamily: 'unemployment-by-province',
    title: 'Unemployment Rate: Saskatchewan',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2064327],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Saskatchewan unemployment rate from the Labour Force Survey, in percent. Provincial rates let you compare labour-market tightness across provinces instead of reading Canada as a single market. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_NS',
    geoFamily: 'unemployment-by-province',
    title: 'Unemployment Rate: Nova Scotia',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2063382],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Nova Scotia unemployment rate from the Labour Force Survey, in percent. Provincial rates let you compare labour-market tightness across provinces instead of reading Canada as a single market. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_NB',
    geoFamily: 'unemployment-by-province',
    title: 'Unemployment Rate: New Brunswick',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2063571],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'New Brunswick unemployment rate from the Labour Force Survey, in percent. Provincial rates let you compare labour-market tightness across provinces instead of reading Canada as a single market. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_NL',
    geoFamily: 'unemployment-by-province',
    title: 'Unemployment Rate: Newfoundland and Labrador',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2063004],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Newfoundland and Labrador unemployment rate from the Labour Force Survey, in percent. Provincial rates let you compare labour-market tightness across provinces instead of reading Canada as a single market. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'UNRATE_PEI',
    geoFamily: 'unemployment-by-province',
    title: 'Unemployment Rate: Prince Edward Island',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Labour Force Survey',
    release: 'Labour Force Survey',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701',
    tableId: '14-10-0287-01',
    vectorIds: [2063193],
    units: 'Percent',
    unitsDetail: 'Seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Prince Edward Island unemployment rate from the Labour Force Survey, in percent. Provincial rates let you compare labour-market tightness across provinces instead of reading Canada as a single market. Seasonally adjusted; published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_MB',
    title: 'CPI: Manitoba',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41692055],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Manitoba all-items CPI on a 2002=100 base, not seasonally adjusted. Provincial CPIs reveal where inflation is running hotter or cooler than the national average. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_SK',
    title: 'CPI: Saskatchewan',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41692191],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Saskatchewan all-items CPI on a 2002=100 base, not seasonally adjusted. Provincial CPIs reveal where inflation is running hotter or cooler than the national average. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_NS',
    title: 'CPI: Nova Scotia',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41691513],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Nova Scotia all-items CPI on a 2002=100 base, not seasonally adjusted. Provincial CPIs reveal where inflation is running hotter or cooler than the national average. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_NB',
    title: 'CPI: New Brunswick',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41691648],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'New Brunswick all-items CPI on a 2002=100 base, not seasonally adjusted. Provincial CPIs reveal where inflation is running hotter or cooler than the national average. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_NL',
    title: 'CPI: Newfoundland and Labrador',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41691244],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Newfoundland and Labrador all-items CPI on a 2002=100 base, not seasonally adjusted. Provincial CPIs reveal where inflation is running hotter or cooler than the national average. Published monthly.',
    lastVerified: V,
  },
  {
    id: 'CPI_PEI',
    title: 'CPI: Prince Edward Island',
    source: 'statcan',
    sourceLabel: 'Statistics Canada, Consumer Price Index',
    release: 'Consumer Price Index',
    releaseUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    sourceUrl: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
    tableId: '18-10-0004-01',
    vectorIds: [41691379],
    units: 'Index, 2002=100',
    unitsDetail: 'Not seasonally adjusted',
    frequency: 'Monthly',
    category: 'provinces-territories-cities',
    description: 'Prince Edward Island all-items CPI on a 2002=100 base, not seasonally adjusted. Provincial CPIs reveal where inflation is running hotter or cooler than the national average. Published monthly.',
    lastVerified: V,
  },
];

/* ---- Helpers expected by the app (derived from the verified SERIES list) ---- */

export const REGISTRY: SeriesMeta[] = SERIES;

export const CATEGORY_LABELS: Record<CategorySlug, string> = Object.fromEntries(
  CATEGORIES.map((c) => [c.slug, c.title])
) as Record<CategorySlug, string>;

export function getSeries(id: string): SeriesMeta | undefined {
  return SERIES.find((s) => s.id === id);
}

export function searchSeries(q: string): SeriesMeta[] {
  const needle = q.trim().toLowerCase();
  if (!needle) return SERIES;
  return SERIES.filter(
    (s) =>
      s.id.toLowerCase().includes(needle) ||
      s.title.toLowerCase().includes(needle) ||
      s.description.toLowerCase().includes(needle) ||
      s.release.toLowerCase().includes(needle) ||
      s.frequency.toLowerCase().includes(needle) ||
      s.sourceLabel.toLowerCase().includes(needle) ||
      s.units.toLowerCase().includes(needle) ||
      (s.unitsDetail ?? '').toLowerCase().includes(needle)
  );
}

